name: finances
description: "financial control app"

publish_to: 'none' 

version: 1.1.00+72

environment:
  sdk: '>=3.1.5 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get_it: ^7.6.4
  firebase_auth: ^4.8.0
  firebase_core: ^2.12.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.18.1
  dynamic_color: ^1.6.8
  flutter_localization: ^0.1.14
  image_picker: ^1.0.4
  flutter_colorpicker: ^1.0.3
  file_picker: ^6.0.0
  package_info_plus: ^4.2.0
  fl_chart: ^0.64.0
  flutter_launcher_icons: ^0.13.1
  restart_app: ^1.2.1
  flutter_swiper_view: ^1.1.8
  logger: ^2.0.2+1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^1.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/finances_icon2.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/icons/finances_icon2.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
    - family: TrademarkIcons
      fonts:
        - asset: assets/fonts/TrademarkIcons.ttf
    - family: FontelloIcons
      fonts:
        - asset: assets/fonts/FontelloIcons.ttf

