// Copyright (C) 2024 rudson
//
// This file is part of finances.
//
// finances is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// finances is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with finances.  If not, see <https://www.gnu.org/licenses/>.
//
import 'package:flutter/widgets.dart';

// selected icons from https://fontello.com/
//
const Map<String, IconData> fontelloIconsCodes = {
  "address-book": IconData(59392, fontFamily: 'FontelloIcons'),
  "adjust-brightness": IconData(59393, fontFamily: 'FontelloIcons'),
  "alimony": IconData(59394, fontFamily: 'FontelloIcons'),
  "anchor-outline": IconData(59395, fontFamily: 'FontelloIcons'),
  "attachment-outline": IconData(59396, fontFamily: 'FontelloIcons'),
  "baby": IconData(59397, fontFamily: 'FontelloIcons'),
  "baby-carriage": IconData(59398, fontFamily: 'FontelloIcons'),
  "baseball": IconData(59399, fontFamily: 'FontelloIcons'),
  "baseball-bat-ball": IconData(59400, fontFamily: 'FontelloIcons'),
  "basketball": IconData(59401, fontFamily: 'FontelloIcons'),
  "basket-shopping": IconData(59402, fontFamily: 'FontelloIcons'),
  "bath": IconData(59403, fontFamily: 'FontelloIcons'),
  "bed": IconData(59404, fontFamily: 'FontelloIcons'),
  "beer": IconData(59405, fontFamily: 'FontelloIcons'),
  "beer-mug-empty": IconData(59406, fontFamily: 'FontelloIcons'),
  "bell": IconData(59407, fontFamily: 'FontelloIcons'),
  "bicycle": IconData(59408, fontFamily: 'FontelloIcons'),
  "bill": IconData(59409, fontFamily: 'FontelloIcons'),
  "bone": IconData(59410, fontFamily: 'FontelloIcons'),
  "book": IconData(59411, fontFamily: 'FontelloIcons'),
  "book-atlas": IconData(59412, fontFamily: 'FontelloIcons'),
  "book-bible": IconData(59413, fontFamily: 'FontelloIcons'),
  "book-bookmark": IconData(59414, fontFamily: 'FontelloIcons'),
  "book-journal-whills": IconData(59415, fontFamily: 'FontelloIcons'),
  "book-medical": IconData(59416, fontFamily: 'FontelloIcons'),
  "book-open": IconData(59417, fontFamily: 'FontelloIcons'),
  "book-open-reader": IconData(59418, fontFamily: 'FontelloIcons'),
  "book-quran": IconData(59419, fontFamily: 'FontelloIcons'),
  "book-skull": IconData(59420, fontFamily: 'FontelloIcons'),
  "book-tanakh": IconData(59421, fontFamily: 'FontelloIcons'),
  "bowling-ball": IconData(59422, fontFamily: 'FontelloIcons'),
  "briefcase": IconData(59423, fontFamily: 'FontelloIcons'),
  "briefcase-medical": IconData(59424, fontFamily: 'FontelloIcons'),
  "brush": IconData(59425, fontFamily: 'FontelloIcons'),
  "btc": IconData(59426, fontFamily: 'FontelloIcons'),
  "budget": IconData(59427, fontFamily: 'FontelloIcons'),
  "budget_outlined_ori": IconData(59428, fontFamily: 'FontelloIcons'),
  "budget_page": IconData(59429, fontFamily: 'FontelloIcons'),
  "bug": IconData(59430, fontFamily: 'FontelloIcons'),
  "building-columns": IconData(59431, fontFamily: 'FontelloIcons'),
  "burger": IconData(59432, fontFamily: 'FontelloIcons'),
  "bus": IconData(59433, fontFamily: 'FontelloIcons'),
  "bus-simple": IconData(59434, fontFamily: 'FontelloIcons'),
  "cake-candles": IconData(59435, fontFamily: 'FontelloIcons'),
  "calculator": IconData(59436, fontFamily: 'FontelloIcons'),
  "calendar": IconData(59437, fontFamily: 'FontelloIcons'),
  "calendar-check": IconData(59438, fontFamily: 'FontelloIcons'),
  "calendar-day": IconData(59439, fontFamily: 'FontelloIcons'),
  "calendar-days": IconData(59440, fontFamily: 'FontelloIcons'),
  "camera": IconData(59441, fontFamily: 'FontelloIcons'),
  "candy-cane": IconData(59442, fontFamily: 'FontelloIcons'),
  "cannabis": IconData(59443, fontFamily: 'FontelloIcons'),
  "capsules": IconData(59444, fontFamily: 'FontelloIcons'),
  "car-rear": IconData(59445, fontFamily: 'FontelloIcons'),
  "cart-flatbed": IconData(59446, fontFamily: 'FontelloIcons'),
  "cart-shopping": IconData(59447, fontFamily: 'FontelloIcons'),
  "cash": IconData(59448, fontFamily: 'FontelloIcons'),
  "cash_bag": IconData(59449, fontFamily: 'FontelloIcons'),
  "cat": IconData(59450, fontFamily: 'FontelloIcons'),
  "champagne-glasses": IconData(59451, fontFamily: 'FontelloIcons'),
  "chart-pie": IconData(59452, fontFamily: 'FontelloIcons'),
  "chart-pie-outline": IconData(59453, fontFamily: 'FontelloIcons'),
  "chess": IconData(59454, fontFamily: 'FontelloIcons'),
  "child": IconData(59455, fontFamily: 'FontelloIcons'),
  "child-dress": IconData(59456, fontFamily: 'FontelloIcons'),
  "child-reaching": IconData(59457, fontFamily: 'FontelloIcons'),
  "children": IconData(59458, fontFamily: 'FontelloIcons'),
  "church": IconData(59459, fontFamily: 'FontelloIcons'),
  "clock": IconData(59460, fontFamily: 'FontelloIcons'),
  "clock-rotate-left": IconData(59461, fontFamily: 'FontelloIcons'),
  "clothes": IconData(59462, fontFamily: 'FontelloIcons'),
  "coffee": IconData(59463, fontFamily: 'FontelloIcons'),
  "cog": IconData(59464, fontFamily: 'FontelloIcons'),
  "cog-outline": IconData(59465, fontFamily: 'FontelloIcons'),
  "computer": IconData(59466, fontFamily: 'FontelloIcons'),
  "contacts": IconData(59467, fontFamily: 'FontelloIcons'),
  "cow": IconData(59468, fontFamily: 'FontelloIcons'),
  "crow": IconData(59469, fontFamily: 'FontelloIcons'),
  "device-desktop": IconData(59470, fontFamily: 'FontelloIcons'),
  "device-laptop": IconData(59471, fontFamily: 'FontelloIcons'),
  "device-phone": IconData(59472, fontFamily: 'FontelloIcons'),
  "device-tablet": IconData(59473, fontFamily: 'FontelloIcons'),
  "dice": IconData(59474, fontFamily: 'FontelloIcons'),
  "dice-d20": IconData(59475, fontFamily: 'FontelloIcons'),
  "display": IconData(59476, fontFamily: 'FontelloIcons'),
  "doctor": IconData(59477, fontFamily: 'FontelloIcons'),
  "dog": IconData(59478, fontFamily: 'FontelloIcons'),
  "dove": IconData(59479, fontFamily: 'FontelloIcons'),
  "down": IconData(59480, fontFamily: 'FontelloIcons'),
  "dragon": IconData(59481, fontFamily: 'FontelloIcons'),
  "drumstick-bite": IconData(59482, fontFamily: 'FontelloIcons'),
  "dumbbell": IconData(59483, fontFamily: 'FontelloIcons'),
  "eye-dropper": IconData(59484, fontFamily: 'FontelloIcons'),
  "feather": IconData(59485, fontFamily: 'FontelloIcons'),
  "feather-pointed": IconData(59486, fontFamily: 'FontelloIcons'),
  "film": IconData(59487, fontFamily: 'FontelloIcons'),
  "filter": IconData(59488, fontFamily: 'FontelloIcons'),
  "fish-fins": IconData(59489, fontFamily: 'FontelloIcons'),
  "football": IconData(59490, fontFamily: 'FontelloIcons'),
  "frog": IconData(59491, fontFamily: 'FontelloIcons'),
  "futbol": IconData(59492, fontFamily: 'FontelloIcons'),
  "gas-pump": IconData(59493, fontFamily: 'FontelloIcons'),
  "gavel": IconData(59494, fontFamily: 'FontelloIcons'),
  "gear": IconData(59495, fontFamily: 'FontelloIcons'),
  "gift": IconData(59496, fontFamily: 'FontelloIcons'),
  "glasses": IconData(59497, fontFamily: 'FontelloIcons'),
  "golf-ball-tee": IconData(59498, fontFamily: 'FontelloIcons'),
  "graduate": IconData(59499, fontFamily: 'FontelloIcons'),
  "graduation-cap": IconData(59500, fontFamily: 'FontelloIcons'),
  "group-outline": IconData(59501, fontFamily: 'FontelloIcons'),
  "hat-wizard": IconData(59502, fontFamily: 'FontelloIcons'),
  "headphones": IconData(59503, fontFamily: 'FontelloIcons'),
  "headset": IconData(59504, fontFamily: 'FontelloIcons'),
  "heart": IconData(59505, fontFamily: 'FontelloIcons'),
  "home-outline": IconData(59506, fontFamily: 'FontelloIcons'),
  "hotdog": IconData(59507, fontFamily: 'FontelloIcons'),
  "hourglass-half": IconData(59508, fontFamily: 'FontelloIcons'),
  "ice-cream": IconData(59509, fontFamily: 'FontelloIcons'),
  "image-outline": IconData(59510, fontFamily: 'FontelloIcons'),
  "joint": IconData(59511, fontFamily: 'FontelloIcons'),
  "leaf": IconData(59512, fontFamily: 'FontelloIcons'),
  "lightbulb": IconData(59513, fontFamily: 'FontelloIcons'),
  "map": IconData(59514, fontFamily: 'FontelloIcons'),
  "map-location-dot": IconData(59515, fontFamily: 'FontelloIcons'),
  "microphone-outline": IconData(59516, fontFamily: 'FontelloIcons'),
  "money": IconData(59517, fontFamily: 'FontelloIcons'),
  "money_flat": IconData(59518, fontFamily: 'FontelloIcons'),
  "motorcycle": IconData(59519, fontFamily: 'FontelloIcons'),
  "news": IconData(59520, fontFamily: 'FontelloIcons'),
  "notes-outline": IconData(59521, fontFamily: 'FontelloIcons'),
  "ofx_archive": IconData(59522, fontFamily: 'FontelloIcons'),
  "ofx_archive_off": IconData(59523, fontFamily: 'FontelloIcons'),
  "ofx_question": IconData(59524, fontFamily: 'FontelloIcons'),
  "palette": IconData(59525, fontFamily: 'FontelloIcons'),
  "pen": IconData(59526, fontFamily: 'FontelloIcons'),
  "pencil": IconData(59527, fontFamily: 'FontelloIcons'),
  "person-praying": IconData(59528, fontFamily: 'FontelloIcons'),
  "person-running": IconData(59529, fontFamily: 'FontelloIcons'),
  "person-skating": IconData(59530, fontFamily: 'FontelloIcons'),
  "person-swimming": IconData(59531, fontFamily: 'FontelloIcons'),
  "phone-outline": IconData(59532, fontFamily: 'FontelloIcons'),
  "pi-outline": IconData(59533, fontFamily: 'FontelloIcons'),
  "pipette": IconData(59534, fontFamily: 'FontelloIcons'),
  "pizza-slice": IconData(59535, fontFamily: 'FontelloIcons'),
  "place-of-worship": IconData(59536, fontFamily: 'FontelloIcons'),
  "poo": IconData(59537, fontFamily: 'FontelloIcons'),
  "puzzle-outline": IconData(59538, fontFamily: 'FontelloIcons'),
  "question": IconData(59539, fontFamily: 'FontelloIcons'),
  "scale-balanced": IconData(59540, fontFamily: 'FontelloIcons'),
  "seedling": IconData(59541, fontFamily: 'FontelloIcons'),
  "select_box": IconData(59542, fontFamily: 'FontelloIcons'),
  "select_check_box": IconData(59543, fontFamily: 'FontelloIcons'),
  "services": IconData(59544, fontFamily: 'FontelloIcons'),
  "shopping-cart": IconData(59545, fontFamily: 'FontelloIcons'),
  "shuffle": IconData(59546, fontFamily: 'FontelloIcons'),
  "social-github-circular": IconData(59547, fontFamily: 'FontelloIcons'),
  "social-instagram": IconData(59548, fontFamily: 'FontelloIcons'),
  "social-instagram-circular": IconData(59549, fontFamily: 'FontelloIcons'),
  "social-linkedin-circular": IconData(59550, fontFamily: 'FontelloIcons'),
  "social-pinterest-circular": IconData(59551, fontFamily: 'FontelloIcons'),
  "social-twitter-circular": IconData(59552, fontFamily: 'FontelloIcons'),
  "social-youtube": IconData(59553, fontFamily: 'FontelloIcons'),
  "social-youtube-circular": IconData(59554, fontFamily: 'FontelloIcons'),
  "sort_by_date": IconData(59555, fontFamily: 'FontelloIcons'),
  "sort_by_priority": IconData(59556, fontFamily: 'FontelloIcons'),
  "sort_by_time": IconData(59557, fontFamily: 'FontelloIcons'),
  "spanner": IconData(59558, fontFamily: 'FontelloIcons'),
  "syringe": IconData(59559, fontFamily: 'FontelloIcons'),
  "taxi": IconData(59560, fontFamily: 'FontelloIcons'),
  "temperature-high": IconData(59561, fontFamily: 'FontelloIcons'),
  "trash-can": IconData(59562, fontFamily: 'FontelloIcons'),
  "tree": IconData(59563, fontFamily: 'FontelloIcons'),
  "up": IconData(59564, fontFamily: 'FontelloIcons'),
  "woodwork": IconData(59565, fontFamily: 'FontelloIcons'),
};
