// Copyright (C) 2024 rudson
//
// This file is part of finances.
//
// finances is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// finances is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with finances.  If not, see <https://www.gnu.org/licenses/>.

import 'package:flutter/widgets.dart';

/// all Icons under MaterialIcons
///
/// https://www.google.com/design/icons/
const Map<String, IconData> materialIconsCodes = {
  'access alarm': IconData(0xe038, fontFamily: 'MaterialIcons'),
  'accessibility': IconData(0xe03c, fontFamily: 'MaterialIcons'),
  'accessible': IconData(0xe03e, fontFamily: 'MaterialIcons'),
  'accessible forward': IconData(0xe03f, fontFamily: 'MaterialIcons'),
  'account balance': IconData(0xe040, fontFamily: 'MaterialIcons'),
  'account box': IconData(0xe042, fontFamily: 'MaterialIcons'),
  'ac unit': IconData(0xe037, fontFamily: 'MaterialIcons'),
  'adb': IconData(0xe046, fontFamily: 'MaterialIcons'),
  'add alarm': IconData(0xe049, fontFamily: 'MaterialIcons'),
  'adf scanner': IconData(0xf04b8, fontFamily: 'MaterialIcons'),
  'admin panel settings': IconData(0xe062, fontFamily: 'MaterialIcons'),
  'adobe': IconData(0xf04b9, fontFamily: 'MaterialIcons'),
  'ads click': IconData(0xf04ba, fontFamily: 'MaterialIcons'),
  'agriculture': IconData(0xe063, fontFamily: 'MaterialIcons'),
  'air': IconData(0xe064, fontFamily: 'MaterialIcons'),
  'airport shuttle': IconData(0xe071, fontFamily: 'MaterialIcons'),
  'alarm': IconData(0xe072, fontFamily: 'MaterialIcons'),
  'all inbox': IconData(0xe07d, fontFamily: 'MaterialIcons'),
  'all inclusive': IconData(0xe07e, fontFamily: 'MaterialIcons'),
  'alternate email': IconData(0xe081, fontFamily: 'MaterialIcons'),
  'alt route': IconData(0xe080, fontFamily: 'MaterialIcons'),
  'analytics': IconData(0xe083, fontFamily: 'MaterialIcons'),
  'anchor': IconData(0xe084, fontFamily: 'MaterialIcons'),
  'android': IconData(0xe085, fontFamily: 'MaterialIcons'),
  'apartment': IconData(0xe089, fontFamily: 'MaterialIcons'),
  'apple': IconData(0xf04be, fontFamily: 'MaterialIcons'),
  'approval': IconData(0xe08e, fontFamily: 'MaterialIcons'),
  'architecture': IconData(0xe090, fontFamily: 'MaterialIcons'),
  'assignment ind': IconData(0xe0a6, fontFamily: 'MaterialIcons'),
  'assistant direction': IconData(0xe0ac, fontFamily: 'MaterialIcons'),
  'assist walker': IconData(0xf0854, fontFamily: 'MaterialIcons'),
  'assured workload': IconData(0xf04c3, fontFamily: 'MaterialIcons'),
  'attach file': IconData(0xe0b1, fontFamily: 'MaterialIcons'),
  'attach money': IconData(0xe0b2, fontFamily: 'MaterialIcons'),
  'attribution': IconData(0xe0b5, fontFamily: 'MaterialIcons'),
  'audiotrack': IconData(0xe0b6, fontFamily: 'MaterialIcons'),
  'auto awesome': IconData(0xe0b7, fontFamily: 'MaterialIcons'),
  'auto graph': IconData(0xe0be, fontFamily: 'MaterialIcons'),
  'auto stories': IconData(0xe0bf, fontFamily: 'MaterialIcons'),
  'av timer': IconData(0xe0c2, fontFamily: 'MaterialIcons'),
  'baby changing station': IconData(0xe0c3, fontFamily: 'MaterialIcons'),
  'back hand': IconData(0xf04c5, fontFamily: 'MaterialIcons'),
  'bakery dining': IconData(0xe0c9, fontFamily: 'MaterialIcons'),
  'balance': IconData(0xf04c6, fontFamily: 'MaterialIcons'),
  'barcode reader': IconData(0xf0855, fontFamily: 'MaterialIcons'),
  'bathtub': IconData(0xe0cf, fontFamily: 'MaterialIcons'),
  'battery charging full': IconData(0xe0d1, fontFamily: 'MaterialIcons'),
  'beach access': IconData(0xe0d6, fontFamily: 'MaterialIcons'),
  'bed': IconData(0xe0d7, fontFamily: 'MaterialIcons'),
  'bedtime': IconData(0xe0db, fontFamily: 'MaterialIcons'),
  'biotech': IconData(0xe0df, fontFamily: 'MaterialIcons'),
  'blender': IconData(0xe0e0, fontFamily: 'MaterialIcons'),
  'blind': IconData(0xf0856, fontFamily: 'MaterialIcons'),
  'bluetooth searching': IconData(0xe0e9, fontFamily: 'MaterialIcons'),
  'bolt': IconData(0xe0ee, fontFamily: 'MaterialIcons'),
  'bookmark border': IconData(0xe0f4, fontFamily: 'MaterialIcons'),
  'border color': IconData(0xe0fa, fontFamily: 'MaterialIcons'),
  'breakfast dining': IconData(0xe104, fontFamily: 'MaterialIcons'),
  'brightness low': IconData(0xe10e, fontFamily: 'MaterialIcons'),
  'browse gallery': IconData(0xf06ba, fontFamily: 'MaterialIcons'),
  'brush': IconData(0xe113, fontFamily: 'MaterialIcons'),
  'bug report': IconData(0xe115, fontFamily: 'MaterialIcons'),
  'build': IconData(0xe116, fontFamily: 'MaterialIcons'),
  'business center': IconData(0xe11c, fontFamily: 'MaterialIcons'),
  'cake': IconData(0xe120, fontFamily: 'MaterialIcons'),
  'calculate': IconData(0xe121, fontFamily: 'MaterialIcons'),
  'calendar month': IconData(0xf06bb, fontFamily: 'MaterialIcons'),
  'calendar today': IconData(0xe122, fontFamily: 'MaterialIcons'),
  'call': IconData(0xe126, fontFamily: 'MaterialIcons'),
  'camera': IconData(0xe12f, fontFamily: 'MaterialIcons'),
  'camera alt': IconData(0xe130, fontFamily: 'MaterialIcons'),
  'campaign': IconData(0xe138, fontFamily: 'MaterialIcons'),
  'card travel': IconData(0xe140, fontFamily: 'MaterialIcons'),
  'carpenter': IconData(0xe141, fontFamily: 'MaterialIcons'),
  'car repair': IconData(0xe13d, fontFamily: 'MaterialIcons'),
  'casino': IconData(0xe143, fontFamily: 'MaterialIcons'),
  'castle': IconData(0xf04cb, fontFamily: 'MaterialIcons'),
  'catching pokemon': IconData(0xe147, fontFamily: 'MaterialIcons'),
  'celebration': IconData(0xe149, fontFamily: 'MaterialIcons'),
  'cell tower': IconData(0xf04cc, fontFamily: 'MaterialIcons'),
  'chair': IconData(0xe14d, fontFamily: 'MaterialIcons'),
  'chair alt': IconData(0xe14e, fontFamily: 'MaterialIcons'),
  'checkroom': IconData(0xe15d, fontFamily: 'MaterialIcons'),
  'child care': IconData(0xe160, fontFamily: 'MaterialIcons'),
  'child friendly': IconData(0xe161, fontFamily: 'MaterialIcons'),
  'church': IconData(0xf04cd, fontFamily: 'MaterialIcons'),
  'cleaning services': IconData(0xe167, fontFamily: 'MaterialIcons'),
  'cloud download': IconData(0xe172, fontFamily: 'MaterialIcons'),
  'cloud queue': IconData(0xe174, fontFamily: 'MaterialIcons'),
  'cloud sync': IconData(0xf04ce, fontFamily: 'MaterialIcons'),
  'cloud upload': IconData(0xe175, fontFamily: 'MaterialIcons'),
  'cloudy snowing': IconData(0xf04cf, fontFamily: 'MaterialIcons'),
  'coffee': IconData(0xe178, fontFamily: 'MaterialIcons'),
  'coffee maker': IconData(0xe179, fontFamily: 'MaterialIcons'),
  'colorize': IconData(0xe17d, fontFamily: 'MaterialIcons'),
  'color lens': IconData(0xe17c, fontFamily: 'MaterialIcons'),
  'commute': IconData(0xe180, fontFamily: 'MaterialIcons'),
  'computer': IconData(0xe185, fontFamily: 'MaterialIcons'),
  'construction': IconData(0xe189, fontFamily: 'MaterialIcons'),
  'content paste': IconData(0xe192, fontFamily: 'MaterialIcons'),
  'cookie': IconData(0xf04d9, fontFamily: 'MaterialIcons'),
  'coronavirus': IconData(0xe199, fontFamily: 'MaterialIcons'),
  'cottage': IconData(0xe19b, fontFamily: 'MaterialIcons'),
  'create': IconData(0xe19d, fontFamily: 'MaterialIcons'),
  'credit card': IconData(0xe19f, fontFamily: 'MaterialIcons'),
  'credit score': IconData(0xe1a1, fontFamily: 'MaterialIcons'),
  'crib': IconData(0xe1a2, fontFamily: 'MaterialIcons'),
  'cruelty free': IconData(0xf04da, fontFamily: 'MaterialIcons'),
  'currency bitcoin': IconData(0xf06bc, fontFamily: 'MaterialIcons'),
  'currency exchange': IconData(0xf04dc, fontFamily: 'MaterialIcons'),
  'currency franc': IconData(0xf04dd, fontFamily: 'MaterialIcons'),
  'currency lira': IconData(0xf04de, fontFamily: 'MaterialIcons'),
  'currency pound': IconData(0xf04df, fontFamily: 'MaterialIcons'),
  'currency ruble': IconData(0xf04e0, fontFamily: 'MaterialIcons'),
  'currency rupee': IconData(0xf04e1, fontFamily: 'MaterialIcons'),
  'currency yen': IconData(0xf04e2, fontFamily: 'MaterialIcons'),
  'currency yuan': IconData(0xf04e3, fontFamily: 'MaterialIcons'),
  'cut': IconData(0xe191, fontFamily: 'MaterialIcons'),
  'deck': IconData(0xe1b7, fontFamily: 'MaterialIcons'),
  'delete outline': IconData(0xe1bb, fontFamily: 'MaterialIcons'),
  'delivery dining': IconData(0xe1bd, fontFamily: 'MaterialIcons'),
  'design services': IconData(0xe1c0, fontFamily: 'MaterialIcons'),
  'devices': IconData(0xe1cb, fontFamily: 'MaterialIcons'),
  'device thermostat': IconData(0xe1c9, fontFamily: 'MaterialIcons'),
  'diamond': IconData(0xf04ed, fontFamily: 'MaterialIcons'),
  'directions bike': IconData(0xe1d2, fontFamily: 'MaterialIcons'),
  'directions boat': IconData(0xe1d3, fontFamily: 'MaterialIcons'),
  'directions bus': IconData(0xe1d5, fontFamily: 'MaterialIcons'),
  'directions bus filled': IconData(0xe1d6, fontFamily: 'MaterialIcons'),
  'directions car': IconData(0xe1d7, fontFamily: 'MaterialIcons'),
  'directions run': IconData(0xe1dc, fontFamily: 'MaterialIcons'),
  'directions walk': IconData(0xe1e1, fontFamily: 'MaterialIcons'),
  'done outline': IconData(0xe1f8, fontFamily: 'MaterialIcons'),
  'downhill skiing': IconData(0xe200, fontFamily: 'MaterialIcons'),
  'draw': IconData(0xf04f3, fontFamily: 'MaterialIcons'),
  'dry': IconData(0xe20d, fontFamily: 'MaterialIcons'),
  'dry cleaning': IconData(0xe20e, fontFamily: 'MaterialIcons'),
  'eco': IconData(0xe217, fontFamily: 'MaterialIcons'),
  'edit': IconData(0xe21a, fontFamily: 'MaterialIcons'),
  'edit calendar': IconData(0xf04f5, fontFamily: 'MaterialIcons'),
  'edit document': IconData(0xf085d, fontFamily: 'MaterialIcons'),
  'edit note': IconData(0xf04f6, fontFamily: 'MaterialIcons'),
  'egg': IconData(0xf04f8, fontFamily: 'MaterialIcons'),
  'egg alt': IconData(0xf04f7, fontFamily: 'MaterialIcons'),
  'elderly': IconData(0xe222, fontFamily: 'MaterialIcons'),
  'elderly woman': IconData(0xf04f9, fontFamily: 'MaterialIcons'),
  'electrical services': IconData(0xe228, fontFamily: 'MaterialIcons'),
  'electric bike': IconData(0xe223, fontFamily: 'MaterialIcons'),
  'electric bolt': IconData(0xf079c, fontFamily: 'MaterialIcons'),
  'electric car': IconData(0xe224, fontFamily: 'MaterialIcons'),
  'electric moped': IconData(0xe225, fontFamily: 'MaterialIcons'),
  'electric rickshaw': IconData(0xe226, fontFamily: 'MaterialIcons'),
  'electric scooter': IconData(0xe227, fontFamily: 'MaterialIcons'),
  'email': IconData(0xe22a, fontFamily: 'MaterialIcons'),
  'emergency': IconData(0xf04fa, fontFamily: 'MaterialIcons'),
  'emoji events': IconData(0xe22c, fontFamily: 'MaterialIcons'),
  'emoji flags': IconData(0xe22d, fontFamily: 'MaterialIcons'),
  'emoji food beverage': IconData(0xe22e, fontFamily: 'MaterialIcons'),
  'emoji objects': IconData(0xe230, fontFamily: 'MaterialIcons'),
  'emoji people': IconData(0xe231, fontFamily: 'MaterialIcons'),
  'engineering': IconData(0xe234, fontFamily: 'MaterialIcons'),
  'euro': IconData(0xe23b, fontFamily: 'MaterialIcons'),
  'event seat': IconData(0xe242, fontFamily: 'MaterialIcons'),
  'ev station': IconData(0xe23d, fontFamily: 'MaterialIcons'),
  'explore': IconData(0xe248, fontFamily: 'MaterialIcons'),
  'extension': IconData(0xe250, fontFamily: 'MaterialIcons'),
  'face': IconData(0xe252, fontFamily: 'MaterialIcons'),
  'face 2': IconData(0xf085f, fontFamily: 'MaterialIcons'),
  'face 3': IconData(0xf0860, fontFamily: 'MaterialIcons'),
  'face 4': IconData(0xf0861, fontFamily: 'MaterialIcons'),
  'face 5': IconData(0xf0862, fontFamily: 'MaterialIcons'),
  'face 6': IconData(0xf0863, fontFamily: 'MaterialIcons'),
  'face retouching natural': IconData(0xe253, fontFamily: 'MaterialIcons'),
  'factory': IconData(0xf04fd, fontFamily: 'MaterialIcons'),
  'family restroom': IconData(0xe257, fontFamily: 'MaterialIcons'),
  'fastfood': IconData(0xe25a, fontFamily: 'MaterialIcons'),
  'favorite border': IconData(0xe25c, fontFamily: 'MaterialIcons'),
  'filter alt': IconData(0xe27a, fontFamily: 'MaterialIcons'),
  'fingerprint': IconData(0xe287, fontFamily: 'MaterialIcons'),
  'fitness center': IconData(0xe28d, fontFamily: 'MaterialIcons'),
  'flag': IconData(0xe28e, fontFamily: 'MaterialIcons'),
  'forest': IconData(0xf050a, fontFamily: 'MaterialIcons'),
  'format paint': IconData(0xe2bb, fontFamily: 'MaterialIcons'),
  'fort': IconData(0xf050e, fontFamily: 'MaterialIcons'),
  'free breakfast': IconData(0xe2ca, fontFamily: 'MaterialIcons'),
  'front hand': IconData(0xf0510, fontFamily: 'MaterialIcons'),
  'front loader': IconData(0xf0868, fontFamily: 'MaterialIcons'),
  'gamepad': IconData(0xe2d0, fontFamily: 'MaterialIcons'),
  'gavel': IconData(0xe2d3, fontFamily: 'MaterialIcons'),
  'girl': IconData(0xf0513, fontFamily: 'MaterialIcons'),
  'group': IconData(0xe2eb, fontFamily: 'MaterialIcons'),
  'groups': IconData(0xe2ee, fontFamily: 'MaterialIcons'),
  'handshake': IconData(0xf06be, fontFamily: 'MaterialIcons'),
  'handyman': IconData(0xe2f2, fontFamily: 'MaterialIcons'),
  'hardware': IconData(0xe2f3, fontFamily: 'MaterialIcons'),
  'headphones': IconData(0xe2ff, fontFamily: 'MaterialIcons'),
  'headset mic': IconData(0xe302, fontFamily: 'MaterialIcons'),
  'highlight': IconData(0xe310, fontFamily: 'MaterialIcons'),
  'hiking': IconData(0xe313, fontFamily: 'MaterialIcons'),
  'home': IconData(0xe318, fontFamily: 'MaterialIcons'),
  'home repair service': IconData(0xe31c, fontFamily: 'MaterialIcons'),
  'home work': IconData(0xe31d, fontFamily: 'MaterialIcons'),
  'hotel': IconData(0xe322, fontFamily: 'MaterialIcons'),
  'hotel class': IconData(0xf051b, fontFamily: 'MaterialIcons'),
  'house': IconData(0xe328, fontFamily: 'MaterialIcons'),
  'icecream': IconData(0xe331, fontFamily: 'MaterialIcons'),
  'inbox': IconData(0xe33a, fontFamily: 'MaterialIcons'),
  'inventory': IconData(0xe349, fontFamily: 'MaterialIcons'),
  'kayaking': IconData(0xe350, fontFamily: 'MaterialIcons'),
  'key': IconData(0xf052b, fontFamily: 'MaterialIcons'),
  'keyboard': IconData(0xe351, fontFamily: 'MaterialIcons'),
  'keyboard voice': IconData(0xe35c, fontFamily: 'MaterialIcons'),
  'king bed': IconData(0xe35d, fontFamily: 'MaterialIcons'),
  'kitesurfing': IconData(0xe35f, fontFamily: 'MaterialIcons'),
  'landscape': IconData(0xe365, fontFamily: 'MaterialIcons'),
  'language': IconData(0xe366, fontFamily: 'MaterialIcons'),
  'laptop': IconData(0xe367, fontFamily: 'MaterialIcons'),
  'layers': IconData(0xe36d, fontFamily: 'MaterialIcons'),
  'light': IconData(0xe379, fontFamily: 'MaterialIcons'),
  'light mode': IconData(0xe37a, fontFamily: 'MaterialIcons'),
  'line axis': IconData(0xf0535, fontFamily: 'MaterialIcons'),
  'liquor': IconData(0xe383, fontFamily: 'MaterialIcons'),
  'local bar': IconData(0xe38c, fontFamily: 'MaterialIcons'),
  'local cafe': IconData(0xe38d, fontFamily: 'MaterialIcons'),
  'local car wash': IconData(0xe38e, fontFamily: 'MaterialIcons'),
  'local dining': IconData(0xe390, fontFamily: 'MaterialIcons'),
  'local drink': IconData(0xe391, fontFamily: 'MaterialIcons'),
  'local florist': IconData(0xe393, fontFamily: 'MaterialIcons'),
  'local gas station': IconData(0xe394, fontFamily: 'MaterialIcons'),
  'local grocery store': IconData(0xe395, fontFamily: 'MaterialIcons'),
  'local hotel': IconData(0xe397, fontFamily: 'MaterialIcons'),
  'local laundry service': IconData(0xe398, fontFamily: 'MaterialIcons'),
  'local library': IconData(0xe399, fontFamily: 'MaterialIcons'),
  'local mall': IconData(0xe39a, fontFamily: 'MaterialIcons'),
  'local movies': IconData(0xe39b, fontFamily: 'MaterialIcons'),
  'local offer': IconData(0xe39c, fontFamily: 'MaterialIcons'),
  'local parking': IconData(0xe39d, fontFamily: 'MaterialIcons'),
  'local pharmacy': IconData(0xe39e, fontFamily: 'MaterialIcons'),
  'local pizza': IconData(0xe3a0, fontFamily: 'MaterialIcons'),
  'local police': IconData(0xe3a2, fontFamily: 'MaterialIcons'),
  'local post office': IconData(0xe3a3, fontFamily: 'MaterialIcons'),
  'local print shop': IconData(0xe3a4, fontFamily: 'MaterialIcons'),
  'local restaurant': IconData(0xe390, fontFamily: 'MaterialIcons'),
  'local shipping': IconData(0xe3a6, fontFamily: 'MaterialIcons'),
  'local taxi': IconData(0xe3a7, fontFamily: 'MaterialIcons'),
  'location city': IconData(0xe3a8, fontFamily: 'MaterialIcons'),
  'location pin': IconData(0xe3ac, fontFamily: 'MaterialIcons'),
  'lock': IconData(0xe3ae, fontFamily: 'MaterialIcons'),
  'lunch dining': IconData(0xe3c2, fontFamily: 'MaterialIcons'),
  'mail': IconData(0xe3c3, fontFamily: 'MaterialIcons'),
  'man': IconData(0xf0538, fontFamily: 'MaterialIcons'),
  'map': IconData(0xe3c8, fontFamily: 'MaterialIcons'),
  'meeting room': IconData(0xe3da, fontFamily: 'MaterialIcons'),
  'mic external on': IconData(0xe3e3, fontFamily: 'MaterialIcons'),
  'mic none': IconData(0xe3e4, fontFamily: 'MaterialIcons'),
  'military tech': IconData(0xe3e7, fontFamily: 'MaterialIcons'),
  'money off': IconData(0xe3f9, fontFamily: 'MaterialIcons'),
  'monitor': IconData(0xe3fb, fontFamily: 'MaterialIcons'),
  'monitor heart': IconData(0xf053d, fontFamily: 'MaterialIcons'),
  'mosque': IconData(0xf053e, fontFamily: 'MaterialIcons'),
  'motorcycle': IconData(0xe40a, fontFamily: 'MaterialIcons'),
  'mouse': IconData(0xe40b, fontFamily: 'MaterialIcons'),
  'movie': IconData(0xe40d, fontFamily: 'MaterialIcons'),
  'music note': IconData(0xe415, fontFamily: 'MaterialIcons'),
  'nightlife': IconData(0xe42d, fontFamily: 'MaterialIcons'),
  'nightlight': IconData(0xe42e, fontFamily: 'MaterialIcons'),
  'notifications active': IconData(0xe450, fontFamily: 'MaterialIcons'),
  'notifications none': IconData(0xe451, fontFamily: 'MaterialIcons'),
  'oil barrel': IconData(0xf07b7, fontFamily: 'MaterialIcons'),
  'outdoor grill': IconData(0xe463, fontFamily: 'MaterialIcons'),
  'paid': IconData(0xe46a, fontFamily: 'MaterialIcons'),
  'pan tool': IconData(0xe46c, fontFamily: 'MaterialIcons'),
  'pan tool alt': IconData(0xf0544, fontFamily: 'MaterialIcons'),
  'park': IconData(0xe478, fontFamily: 'MaterialIcons'),
  'paste': IconData(0xe192, fontFamily: 'MaterialIcons'),
  'pause circle': IconData(0xe47d, fontFamily: 'MaterialIcons'),
  'pedal bike': IconData(0xe483, fontFamily: 'MaterialIcons'),
  'people': IconData(0xe486, fontFamily: 'MaterialIcons'),
  'pets': IconData(0xe4a1, fontFamily: 'MaterialIcons'),
  'phishing': IconData(0xf0548, fontFamily: 'MaterialIcons'),
  'phone': IconData(0xe4a2, fontFamily: 'MaterialIcons'),
  'phone android': IconData(0xe4a3, fontFamily: 'MaterialIcons'),
  'piano': IconData(0xe4be, fontFamily: 'MaterialIcons'),
  'plumbing': IconData(0xe4d5, fontFamily: 'MaterialIcons'),
  'pool': IconData(0xe4dc, fontFamily: 'MaterialIcons'),
  'power': IconData(0xe4e0, fontFamily: 'MaterialIcons'),
  'power settings new': IconData(0xe4e3, fontFamily: 'MaterialIcons'),
  'precision manufacturing': IconData(0xe4e4, fontFamily: 'MaterialIcons'),
  'pregnant woman': IconData(0xe4e5, fontFamily: 'MaterialIcons'),
  'print': IconData(0xe4ea, fontFamily: 'MaterialIcons'),
  'privacy tip': IconData(0xe4ed, fontFamily: 'MaterialIcons'),
  'public': IconData(0xe4f0, fontFamily: 'MaterialIcons'),
  'push pin': IconData(0xe4f4, fontFamily: 'MaterialIcons'),
  'radio': IconData(0xe502, fontFamily: 'MaterialIcons'),
  'ramen dining': IconData(0xe506, fontFamily: 'MaterialIcons'),
  'recycling': IconData(0xf055a, fontFamily: 'MaterialIcons'),
  'restaurant': IconData(0xe532, fontFamily: 'MaterialIcons'),
  'restaurant menu': IconData(0xe533, fontFamily: 'MaterialIcons'),
  'rocket': IconData(0xf055c, fontFamily: 'MaterialIcons'),
  'rocket launch': IconData(0xf055d, fontFamily: 'MaterialIcons'),
  'roofing': IconData(0xe53a, fontFamily: 'MaterialIcons'),
  'sailing': IconData(0xe54d, fontFamily: 'MaterialIcons'),
  'satellite alt': IconData(0xf0562, fontFamily: 'MaterialIcons'),
  'scanner': IconData(0xe554, fontFamily: 'MaterialIcons'),
  'school': IconData(0xe559, fontFamily: 'MaterialIcons'),
  'science': IconData(0xe55a, fontFamily: 'MaterialIcons'),
  'scuba diving': IconData(0xf06c2, fontFamily: 'MaterialIcons'),
  'sd card': IconData(0xe564, fontFamily: 'MaterialIcons'),
  'self improvement': IconData(0xe56f, fontFamily: 'MaterialIcons'),
  'settings': IconData(0xe57f, fontFamily: 'MaterialIcons'),
  'shelves': IconData(0xf0877, fontFamily: 'MaterialIcons'),
  'shield': IconData(0xe596, fontFamily: 'MaterialIcons'),
  'shopify': IconData(0xf0567, fontFamily: 'MaterialIcons'),
  'shopping bag': IconData(0xe59a, fontFamily: 'MaterialIcons'),
  'shopping basket': IconData(0xe59b, fontFamily: 'MaterialIcons'),
  'shopping cart': IconData(0xe59c, fontFamily: 'MaterialIcons'),
  'sign language': IconData(0xf07c3, fontFamily: 'MaterialIcons'),
  'skateboarding': IconData(0xe5bc, fontFamily: 'MaterialIcons'),
  'sledding': IconData(0xe5bf, fontFamily: 'MaterialIcons'),
  'smoking rooms': IconData(0xe5c8, fontFamily: 'MaterialIcons'),
  'snowboarding': IconData(0xe5cd, fontFamily: 'MaterialIcons'),
  'snowmobile': IconData(0xe5ce, fontFamily: 'MaterialIcons'),
  'snowshoeing': IconData(0xe5cf, fontFamily: 'MaterialIcons'),
  'soap': IconData(0xe5d0, fontFamily: 'MaterialIcons'),
  'soup kitchen': IconData(0xf056c, fontFamily: 'MaterialIcons'),
  'spa': IconData(0xe5d8, fontFamily: 'MaterialIcons'),
  'sports bar': IconData(0xe5e4, fontFamily: 'MaterialIcons'),
  'sports baseball': IconData(0xe5e5, fontFamily: 'MaterialIcons'),
  'sports basketball': IconData(0xe5e6, fontFamily: 'MaterialIcons'),
  'sports cricket': IconData(0xe5e7, fontFamily: 'MaterialIcons'),
  'sports esports': IconData(0xe5e8, fontFamily: 'MaterialIcons'),
  'sports football': IconData(0xe5e9, fontFamily: 'MaterialIcons'),
  'sports golf': IconData(0xe5ea, fontFamily: 'MaterialIcons'),
  'sports gymnastics': IconData(0xf06c3, fontFamily: 'MaterialIcons'),
  'sports handball': IconData(0xe5eb, fontFamily: 'MaterialIcons'),
  'sports hockey': IconData(0xe5ec, fontFamily: 'MaterialIcons'),
  'sports kabaddi': IconData(0xe5ed, fontFamily: 'MaterialIcons'),
  'sports martial arts': IconData(0xf056f, fontFamily: 'MaterialIcons'),
  'sports mma': IconData(0xe5ee, fontFamily: 'MaterialIcons'),
  'sports motorsports': IconData(0xe5ef, fontFamily: 'MaterialIcons'),
  'sports rugby': IconData(0xe5f0, fontFamily: 'MaterialIcons'),
  'sports score': IconData(0xe5f1, fontFamily: 'MaterialIcons'),
  'sports soccer': IconData(0xe5f2, fontFamily: 'MaterialIcons'),
  'sports tennis': IconData(0xe5f3, fontFamily: 'MaterialIcons'),
  'sports volleyball': IconData(0xe5f4, fontFamily: 'MaterialIcons'),
  'stadium': IconData(0xf0572, fontFamily: 'MaterialIcons'),
  'star border': IconData(0xe5fa, fontFamily: 'MaterialIcons'),
  'star border purple500': IconData(0xe5fb, fontFamily: 'MaterialIcons'),
  'store': IconData(0xe60a, fontFamily: 'MaterialIcons'),
  'storefront': IconData(0xe60c, fontFamily: 'MaterialIcons'),
  'store mall directory': IconData(0xe60b, fontFamily: 'MaterialIcons'),
  'stroller': IconData(0xe612, fontFamily: 'MaterialIcons'),
  'style': IconData(0xe613, fontFamily: 'MaterialIcons'),
  'sunny': IconData(0xf0575, fontFamily: 'MaterialIcons'),
  'surfing': IconData(0xe622, fontFamily: 'MaterialIcons'),
  'synagogue': IconData(0xf0582, fontFamily: 'MaterialIcons'),
  'table bar': IconData(0xf0584, fontFamily: 'MaterialIcons'),
  'temple buddhist': IconData(0xf0587, fontFamily: 'MaterialIcons'),
  'temple hindu': IconData(0xf0588, fontFamily: 'MaterialIcons'),
  'terrain': IconData(0xe648, fontFamily: 'MaterialIcons'),
  'theater comedy': IconData(0xe654, fontFamily: 'MaterialIcons'),
  'theaters': IconData(0xe655, fontFamily: 'MaterialIcons'),
  'thermostat': IconData(0xe656, fontFamily: 'MaterialIcons'),
  'traffic': IconData(0xe674, fontFamily: 'MaterialIcons'),
  'trolley': IconData(0xf0878, fontFamily: 'MaterialIcons'),
  'tsunami': IconData(0xf07cf, fontFamily: 'MaterialIcons'),
  'tv': IconData(0xe687, fontFamily: 'MaterialIcons'),
  'umbrella': IconData(0xe68a, fontFamily: 'MaterialIcons'),
  'vaccines': IconData(0xf0597, fontFamily: 'MaterialIcons'),
  'wallet': IconData(0xe041, fontFamily: 'MaterialIcons'),
  'wc': IconData(0xe6dc, fontFamily: 'MaterialIcons'),
  'weekend': IconData(0xe6e1, fontFamily: 'MaterialIcons'),
  'wind power': IconData(0xf07da, fontFamily: 'MaterialIcons'),
  'wine bar': IconData(0xe6f1, fontFamily: 'MaterialIcons'),
  'woman': IconData(0xf05ab, fontFamily: 'MaterialIcons'),
};
