// Copyright (C) 2024 rudson
//
// This file is part of finances.
//
// finances is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// finances is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with finances.  If not, see <https://www.gnu.org/licenses/>.

//
import 'package:flutter/widgets.dart';

// trademarks Icons Codes
//
const Map<String, IconData> trademarksIconsCodes = {
  "a3m": IconData(59392, fontFamily: 'TrademarkIcons'),
  "acclaim": IconData(59393, fontFamily: 'TrademarkIcons'),
  "acer": IconData(59394, fontFamily: 'TrademarkIcons'),
  "activision": IconData(59395, fontFamily: 'TrademarkIcons'),
  "acura": IconData(59396, fontFamily: 'TrademarkIcons'),
  "adblock": IconData(59397, fontFamily: 'TrademarkIcons'),
  "adguard": IconData(59398, fontFamily: 'TrademarkIcons'),
  "airbus": IconData(59399, fontFamily: 'TrademarkIcons'),
  "aircanada": IconData(59400, fontFamily: 'TrademarkIcons'),
  "aliexpress": IconData(59401, fontFamily: 'TrademarkIcons'),
  "amazon": IconData(59402, fontFamily: 'TrademarkIcons'),
  "amd": IconData(59403, fontFamily: 'TrademarkIcons'),
  "americanairlines": IconData(59404, fontFamily: 'TrademarkIcons'),
  "americanexpress": IconData(59405, fontFamily: 'TrademarkIcons'),
  "amp": IconData(59406, fontFamily: 'TrademarkIcons'),
  "analogue": IconData(59407, fontFamily: 'TrademarkIcons'),
  "anchor": IconData(59408, fontFamily: 'TrademarkIcons'),
  "andela": IconData(59409, fontFamily: 'TrademarkIcons'),
  "android": IconData(59410, fontFamily: 'TrademarkIcons'),
  "apple": IconData(59411, fontFamily: 'TrademarkIcons'),
  "aqua": IconData(59412, fontFamily: 'TrademarkIcons'),
  "arcelormittal": IconData(59413, fontFamily: 'TrademarkIcons'),
  "argos": IconData(59414, fontFamily: 'TrademarkIcons'),
  "arm": IconData(59415, fontFamily: 'TrademarkIcons'),
  "asus": IconData(59416, fontFamily: 'TrademarkIcons'),
  "atari": IconData(59417, fontFamily: 'TrademarkIcons'),
  "atom": IconData(59418, fontFamily: 'TrademarkIcons'),
  "audi": IconData(59419, fontFamily: 'TrademarkIcons'),
  "awesomelists": IconData(59420, fontFamily: 'TrademarkIcons'),
  "bankofamerica": IconData(59421, fontFamily: 'TrademarkIcons'),
  "bitcoin": IconData(59422, fontFamily: 'TrademarkIcons'),
  "bbc": IconData(59423, fontFamily: 'TrademarkIcons'),
  "blazor": IconData(59424, fontFamily: 'TrademarkIcons'),
  "blender": IconData(59425, fontFamily: 'TrademarkIcons'),
  "blogger": IconData(59426, fontFamily: 'TrademarkIcons'),
  "blueprint": IconData(59427, fontFamily: 'TrademarkIcons'),
  "bluetooth": IconData(59428, fontFamily: 'TrademarkIcons'),
  "bmw": IconData(59429, fontFamily: 'TrademarkIcons'),
  "bradesco_bank": IconData(59430, fontFamily: 'TrademarkIcons'),
  "brasil_bank": IconData(59431, fontFamily: 'TrademarkIcons'),
  "brave": IconData(59432, fontFamily: 'TrademarkIcons'),
  "btc": IconData(59433, fontFamily: 'TrademarkIcons'),
  "btgpactual_org": IconData(59434, fontFamily: 'TrademarkIcons'),
  "buffer": IconData(59435, fontFamily: 'TrademarkIcons'),
  "burgerking": IconData(59436, fontFamily: 'TrademarkIcons'),
  "caixa_economica_bank": IconData(59437, fontFamily: 'TrademarkIcons'),
  "carrefour": IconData(59438, fontFamily: 'TrademarkIcons'),
  "cbs": IconData(59439, fontFamily: 'TrademarkIcons'),
  "chase_bank": IconData(59440, fontFamily: 'TrademarkIcons'),
  "chevrolet": IconData(59441, fontFamily: 'TrademarkIcons'),
  "cisco": IconData(59442, fontFamily: 'TrademarkIcons'),
  "citibank": IconData(59443, fontFamily: 'TrademarkIcons'),
  "citroen": IconData(59444, fontFamily: 'TrademarkIcons'),
  "cloud66": IconData(59445, fontFamily: 'TrademarkIcons'),
  "cloudflare": IconData(59446, fontFamily: 'TrademarkIcons'),
  "cnn": IconData(59447, fontFamily: 'TrademarkIcons'),
  "cocacola": IconData(59448, fontFamily: 'TrademarkIcons'),
  "commerzbank": IconData(59449, fontFamily: 'TrademarkIcons'),
  "counterstrike": IconData(59450, fontFamily: 'TrademarkIcons'),
  "cplusplus": IconData(59451, fontFamily: 'TrademarkIcons'),
  "dcentertainment": IconData(59452, fontFamily: 'TrademarkIcons'),
  "debian": IconData(59453, fontFamily: 'TrademarkIcons'),
  "dell": IconData(59454, fontFamily: 'TrademarkIcons'),
  "deutschebank": IconData(59455, fontFamily: 'TrademarkIcons'),
  "discord": IconData(59456, fontFamily: 'TrademarkIcons'),
  "dropbox": IconData(59457, fontFamily: 'TrademarkIcons'),
  "ea": IconData(59458, fontFamily: 'TrademarkIcons'),
  "facebook": IconData(59459, fontFamily: 'TrademarkIcons'),
  "flutter": IconData(59460, fontFamily: 'TrademarkIcons'),
  "fox": IconData(59461, fontFamily: 'TrademarkIcons'),
  "foxbit": IconData(59462, fontFamily: 'TrademarkIcons'),
  "freebsd": IconData(59463, fontFamily: 'TrademarkIcons'),
  "freelancer": IconData(59464, fontFamily: 'TrademarkIcons'),
  "generalelectric": IconData(59465, fontFamily: 'TrademarkIcons'),
  "generalmotors": IconData(59466, fontFamily: 'TrademarkIcons'),
  "gentoo": IconData(59467, fontFamily: 'TrademarkIcons'),
  "gimp": IconData(59468, fontFamily: 'TrademarkIcons'),
  "git": IconData(59469, fontFamily: 'TrademarkIcons'),
  "github": IconData(59470, fontFamily: 'TrademarkIcons'),
  "gnu": IconData(59471, fontFamily: 'TrademarkIcons'),
  "go": IconData(59472, fontFamily: 'TrademarkIcons'),
  "goldman_sachs_bank": IconData(59473, fontFamily: 'TrademarkIcons'),
  "google": IconData(59474, fontFamily: 'TrademarkIcons'),
  "googleads": IconData(59475, fontFamily: 'TrademarkIcons'),
  "googleadsense": IconData(59476, fontFamily: 'TrademarkIcons'),
  "googleanalytics": IconData(59477, fontFamily: 'TrademarkIcons'),
  "googleclassroom": IconData(59478, fontFamily: 'TrademarkIcons'),
  "googlemeet": IconData(59479, fontFamily: 'TrademarkIcons'),
  "googleplay": IconData(59480, fontFamily: 'TrademarkIcons'),
  "handyman_black_24dp": IconData(59481, fontFamily: 'TrademarkIcons'),
  "hasura": IconData(59482, fontFamily: 'TrademarkIcons'),
  "hbo": IconData(59483, fontFamily: 'TrademarkIcons'),
  "honda": IconData(59484, fontFamily: 'TrademarkIcons'),
  "hp": IconData(59485, fontFamily: 'TrademarkIcons'),
  "hyundai": IconData(59486, fontFamily: 'TrademarkIcons'),
  "inter_bank": IconData(59487, fontFamily: 'TrademarkIcons'),
  "itaubank": IconData(59488, fontFamily: 'TrademarkIcons'),
  "kde": IconData(59489, fontFamily: 'TrademarkIcons'),
  "kodi": IconData(59490, fontFamily: 'TrademarkIcons'),
  "konami": IconData(59491, fontFamily: 'TrademarkIcons'),
  "linkedin": IconData(59492, fontFamily: 'TrademarkIcons'),
  "linux": IconData(59493, fontFamily: 'TrademarkIcons'),
  "linuxmint": IconData(59494, fontFamily: 'TrademarkIcons'),
  "local_cafe_black_24dp": IconData(59495, fontFamily: 'TrademarkIcons'),
  "logitech": IconData(59496, fontFamily: 'TrademarkIcons'),
  "lunch_dining_black_24dp": IconData(59497, fontFamily: 'TrademarkIcons'),
  "mastercard": IconData(59498, fontFamily: 'TrademarkIcons'),
  "mastercard_2": IconData(59499, fontFamily: 'TrademarkIcons'),
  "mastercard_card": IconData(59500, fontFamily: 'TrademarkIcons'),
  "mcdonalds": IconData(59501, fontFamily: 'TrademarkIcons'),
  "mercadopago": IconData(59502, fontFamily: 'TrademarkIcons'),
  "mercedes": IconData(59503, fontFamily: 'TrademarkIcons'),
  "microsoftbing": IconData(59504, fontFamily: 'TrademarkIcons'),
  "mitsubishi": IconData(59505, fontFamily: 'TrademarkIcons'),
  "motorola": IconData(59506, fontFamily: 'TrademarkIcons'),
  "msi": IconData(59507, fontFamily: 'TrademarkIcons'),
  "nike": IconData(59508, fontFamily: 'TrademarkIcons'),
  "nintendo": IconData(59509, fontFamily: 'TrademarkIcons'),
  "nintendoswitch": IconData(59510, fontFamily: 'TrademarkIcons'),
  "nordvpn": IconData(59511, fontFamily: 'TrademarkIcons'),
  "nubank": IconData(59512, fontFamily: 'TrademarkIcons'),
  "nvidia": IconData(59513, fontFamily: 'TrademarkIcons'),
  "obsstudio": IconData(59514, fontFamily: 'TrademarkIcons'),
  "openai": IconData(59515, fontFamily: 'TrademarkIcons'),
  "opengl": IconData(59516, fontFamily: 'TrademarkIcons'),
  "opensuse": IconData(59517, fontFamily: 'TrademarkIcons'),
  "origin": IconData(59518, fontFamily: 'TrademarkIcons'),
  "pandora": IconData(59519, fontFamily: 'TrademarkIcons'),
  "patreon": IconData(59520, fontFamily: 'TrademarkIcons'),
  "paypal": IconData(59521, fontFamily: 'TrademarkIcons'),
  "pepsi": IconData(59522, fontFamily: 'TrademarkIcons'),
  "php": IconData(59523, fontFamily: 'TrademarkIcons'),
  "phpmyadmin": IconData(59524, fontFamily: 'TrademarkIcons'),
  "picpay": IconData(59525, fontFamily: 'TrademarkIcons'),
  "pix": IconData(59526, fontFamily: 'TrademarkIcons'),
  "playstation": IconData(59527, fontFamily: 'TrademarkIcons'),
  "pnc_bank": IconData(59528, fontFamily: 'TrademarkIcons'),
  "postgresql": IconData(59529, fontFamily: 'TrademarkIcons'),
  "raspberrypi": IconData(59530, fontFamily: 'TrademarkIcons'),
  "restaurant_black_24dp": IconData(59531, fontFamily: 'TrademarkIcons'),
  "restaurant_menu_black_24dp": IconData(59532, fontFamily: 'TrademarkIcons'),
  "rico_org": IconData(59533, fontFamily: 'TrademarkIcons'),
  "safra_bank": IconData(59534, fontFamily: 'TrademarkIcons'),
  "santander_bank": IconData(59535, fontFamily: 'TrademarkIcons'),
  "select_check_box": IconData(59536, fontFamily: 'TrademarkIcons'),
  "starlingbank": IconData(59537, fontFamily: 'TrademarkIcons'),
  "twitch": IconData(59538, fontFamily: 'TrademarkIcons'),
  "twitter": IconData(59539, fontFamily: 'TrademarkIcons'),
  "uber": IconData(59540, fontFamily: 'TrademarkIcons'),
  "ubisoft": IconData(59541, fontFamily: 'TrademarkIcons'),
  "ubuntu": IconData(59542, fontFamily: 'TrademarkIcons'),
  "ufc": IconData(59543, fontFamily: 'TrademarkIcons'),
  "unity": IconData(59544, fontFamily: 'TrademarkIcons'),
  "unrealengine": IconData(59545, fontFamily: 'TrademarkIcons'),
  "upwork": IconData(59546, fontFamily: 'TrademarkIcons'),
  "us_bank": IconData(59547, fontFamily: 'TrademarkIcons'),
  "vale": IconData(59548, fontFamily: 'TrademarkIcons'),
  "valve": IconData(59549, fontFamily: 'TrademarkIcons'),
  "vendor-android": IconData(59550, fontFamily: 'TrademarkIcons'),
  "vendor-apple": IconData(59551, fontFamily: 'TrademarkIcons'),
  "vendor-microsoft": IconData(59552, fontFamily: 'TrademarkIcons'),
  "viber": IconData(59553, fontFamily: 'TrademarkIcons'),
  "vim": IconData(59554, fontFamily: 'TrademarkIcons'),
  "vimeo": IconData(59555, fontFamily: 'TrademarkIcons'),
  "virgin": IconData(59556, fontFamily: 'TrademarkIcons'),
  "visa": IconData(59557, fontFamily: 'TrademarkIcons'),
  "visa_2": IconData(59558, fontFamily: 'TrademarkIcons'),
  "visa_card": IconData(59559, fontFamily: 'TrademarkIcons'),
  "visa_card_inv": IconData(59560, fontFamily: 'TrademarkIcons'),
  "visualstudiocode": IconData(59561, fontFamily: 'TrademarkIcons'),
  "vlcmediaplayer": IconData(59562, fontFamily: 'TrademarkIcons'),
  "volkswagen": IconData(59563, fontFamily: 'TrademarkIcons'),
  "volvo": IconData(59564, fontFamily: 'TrademarkIcons'),
  "vulkan": IconData(59565, fontFamily: 'TrademarkIcons'),
  "waze": IconData(59566, fontFamily: 'TrademarkIcons'),
  "webgl": IconData(59567, fontFamily: 'TrademarkIcons'),
  "westerndigital": IconData(59568, fontFamily: 'TrademarkIcons'),
  "whatsapp": IconData(59569, fontFamily: 'TrademarkIcons'),
  "wii": IconData(59570, fontFamily: 'TrademarkIcons'),
  "wikipedia": IconData(59571, fontFamily: 'TrademarkIcons'),
  "windicss": IconData(59572, fontFamily: 'TrademarkIcons'),
  "windowsxp": IconData(59573, fontFamily: 'TrademarkIcons'),
  "woo": IconData(59574, fontFamily: 'TrademarkIcons'),
  "xbox": IconData(59575, fontFamily: 'TrademarkIcons'),
  "xdotorg": IconData(59576, fontFamily: 'TrademarkIcons'),
  "xero": IconData(59577, fontFamily: 'TrademarkIcons'),
  "xfce": IconData(59578, fontFamily: 'TrademarkIcons'),
  "xp_investimentos": IconData(59579, fontFamily: 'TrademarkIcons'),
  "yahoo": IconData(59580, fontFamily: 'TrademarkIcons'),
  "yale": IconData(59581, fontFamily: 'TrademarkIcons'),
  "yamahamotorcorporation": IconData(59582, fontFamily: 'TrademarkIcons'),
  "youtube": IconData(59583, fontFamily: 'TrademarkIcons'),
};
