// Copyright (C) 2024 rudson
//
// This file is part of finances.
//
// finances is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// finances is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with finances. If not, see <https://www.gnu.org/licenses/>.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_MaH2lliIqADxxTwTTDsRu9rZA6f18kI',
    appId: '1:828903492310:web:0e919b3ccbff995d909777',
    messagingSenderId: '828903492310',
    projectId: 'finances-148e6',
    authDomain: 'finances-148e6.firebaseapp.com',
    storageBucket: 'finances-148e6.appspot.com',
    measurementId: 'G-QQ8EBRMD18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBJIakPsCReNInTxylF0pPl_G3S5-IyyQ',
    appId: '1:828903492310:android:9af92779f8417692909777',
    messagingSenderId: '828903492310',
    projectId: 'finances-148e6',
    storageBucket: 'finances-148e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDScwKsAkQkXEwk4rLYn7WPn96cTDO1fvk',
    appId: '1:828903492310:ios:a4c41c126ab29ffb909777',
    messagingSenderId: '828903492310',
    projectId: 'finances-148e6',
    storageBucket: 'finances-148e6.appspot.com',
    iosClientId: '828903492310-jp6eaq9mrq6heg1mj94hb4oscq34ougd.apps.googleusercontent.com',
    iosBundleId: 'br.com.jrblog.finances.finances',
  );
}
