// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVLmjsuXMq1xmCpTNx5ELIzaLZBE-YJyk',
    appId: '1:515033499857:web:48b7cb485a8645b47f1df0',
    messagingSenderId: '515033499857',
    projectId: 'finance-ed28c',
    authDomain: 'finance-ed28c.firebaseapp.com',
    storageBucket: 'finance-ed28c.appspot.com',
    measurementId: 'G-Z4F9R5DD0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtongZpdkpixgzoDS4Nbz8cXkQYP_WZ1c',
    appId: '1:515033499857:android:8dddce5b61f107cf7f1df0',
    messagingSenderId: '515033499857',
    projectId: 'finance-ed28c',
    storageBucket: 'finance-ed28c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmF2DNGOkP8L4NjZ_g1ipfW8zXbSueZv0',
    appId: '1:515033499857:ios:b4b380ce4085e6177f1df0',
    messagingSenderId: '515033499857',
    projectId: 'finance-ed28c',
    storageBucket: 'finance-ed28c.appspot.com',
    iosBundleId: 'br.com.jrblog.finance',
  );
}
